# vagrant.yml
---
- name: add epel repo
  become: yes
  yum:
    name: epel-release
    state: present
  tags:
    - configuration
    - openconnect

- name: install
  become: yes
  yum:
    name: "NetworkManager-openconnect"
    state: latest
  tags:
    - configuration
    - openconnect
