# Ansible Playbook to install standard Developer tools
# onto a CentOS 7 workstation.
#
# Author: Hank Preston "hank.preston@gmail.com"
---
- name: Setup localhost as DevBox
  hosts: localhost

  roles:
    - users
    - common
    - xrdp
    - python
    - docker
    # - node  # ToDo - Currently getting error
    - openconnect
    - atom
    - postman
    - chrome
    - ngrok

- name: Extra configuration steps
  hosts: localhost
  become: yes

  tasks:
    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Restart docker
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ general.user }}"
        group: docker
        append: yes
