# node.yml
---

- name: check if nvm installed
  become: yes
  become_user: "{{nvm.user}}"
  stat: path=~/.nvm
  register: nvm_path
  changed_when: False
  tags: nvm

- name: Install nvm
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version={{ nvm.version }}
  become: yes
  become_user: "{{ nvm.user }}"
  tags: nvm

- name: source nvm in ~/.bashrc
  become: yes
  become_user: "{{nvm.user}}"
  lineinfile: >
    dest=~/.bashrc
    line="source ~/.nvm/nvm.sh"
  tags: nvm

- name: check installed node version
  become: yes
  become_user: "{{nvm.user}}"
  command: bash -c '. ~/.nvm/nvm.sh; nvm ls'
  register: nvm_install_result
  changed_when: False
  ignore_errors: True
  tags: nvm

- name: install nodejs using nvm
  become: yes
  become_user: "{{nvm.user}}"
  command: bash -c '. ~/.nvm/nvm.sh; nvm install {{ nvm.node_version }}'
  when: nvm_install_result|failed or nvm_install_result.stdout.find('{{nvm.node_version}}') == -1
  tags: nvm
