# common.yml
---

- name: Set timezone to {{ general.timezone }}
  become: yes
  ignore_errors: yes
  command: "timedatectl set-timezone {{ general.timezone }}"
  tags:
    - timezone

- name: Install dependencies
  become: yes
  yum: name={{ item }} state=latest
  with_items:
    - git
    - curl
    - openssl-devel
    - wget
    - telnet

- name: install the 'XWindows' environment group
  yum:
    name: "@X Window System"
    state: present
  become: yes
  tags:
    - gnome

- name: Install gnome minimal
  become: yes
  yum: name={{ item }} state=latest
  with_items:
    - gnome-classic-session
    - gnome-terminal
    #- nautilus-open-terminal
    - control-center
    - liberation-mono-fonts
    - firefox
    - gedit
  tags:
    - gnome

- name: Configure gedit settings
  become: yes
  become_user: "{{ general.user }}"
  with_items:
    - tabs-size 4
    - insert-spaces true
    - display-line-numbers true
    - bracket-matching true
  command: "gsettings set org.gnome.gedit.preferences.editor {{ item }}"
  tags:
    - gnome


- name: set GUI to launch on startup
  become: yes
  command: "systemctl set-default graphical.target"
  tags:
    - gnome

- name: Install Common Fonts
  become: yes
  yum:
    name: "@Fonts"
    state: present

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present
  become: yes

- name: create (shortcut) directory
  become: yes
  file:
    path: "{{ general.home_dir }}/Desktop"
    state: directory
    owner: "{{ general.user }}"
  tags:
    - configuration

- name: install firfox shortcuts
  become: yes
  become_user: "{{ general.user }}"
  template:
    src: "roles/common/templates/firefox.desktop.j2"
    dest: "{{ general.home_dir }}/Desktop/firefox.desktop"
    owner: "{{ general.user }}"
    mode: 0755
  tags:
    - configuration

- name: install terminal shortcuts
  become: yes
  become_user: "{{ general.user }}"
  template:
    src: "roles/common/templates/gnome-terminal.desktop.j2"
    dest: "{{ general.home_dir }}/Desktop/gnome-terminal.desktop"
    owner: "{{ general.user }}"
    mode: 0755
  tags:
    - configuration

- name: install gedit shortcuts
  become: yes
  become_user: "{{ general.user }}"
  template:
    src: "roles/common/templates/gedit.desktop.j2"
    dest: "{{ general.home_dir }}/Desktop/gedit.desktop"
    owner: "{{ general.user }}"
    mode: 0755
  tags:
    - configuration


# - name: remove vagrant from login screen
#   become: yes
#   template:
#     src: "roles/common/templates/vagrant.j2"
#     dest: "/var/lib/AccountsService/users/vagrant"
#     mode: 0644
#   tags:
#     - configuration

# https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
# - name: restart machine
#   shell: sleep 2 && shutdown -r now "Ansible updates triggered"
#   async: 1
#   poll: 0
#   sudo: true
#   ignore_errors: true
#
# - name: waiting for server to come back
#   local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=30
#   sudo: false
