# user.yml
---
- group: name=devbox state=present
  become: yes

- group: name=docker state=present
  become: yes
  tags:
    - user

- name: Create End User {{ general.user }}
  user:
    name: "{{ general.user }}"
    password: "{{ general. password }}"
    shell: /bin/bash
    update_password: always
  become: yes
  tags:
    - user

- name: Add user to groups
  user:
    name: "{{ general.user }}"
    group: "{{ item }}"
    append: yes
  with_items:
    - devbox
    - docker
    - wheel
  become: yes
  tags:
    - user

- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  tags:
    - user

- name: Create default .bash_profile
  become: yes
  template:
    src: "templates/.bash_profile.j2"
    dest: "{{ general.home_dir }}/.bash_profile"
    owner: "{{ general.user }}"
    group: "{{ general.user }}"
    mode: 0744
